# Generated by Django 4.2.5 on 2023-10-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('symbol', models.CharField(default='', max_length=10)),
                ('description', models.TextField(default='')),
                ('token_symbol', models.CharField(default='', max_length=10)),
                ('photos', models.TextField(default='')),
                ('links', models.TextField(default='')),
                ('goal', models.IntegerField(default=0)),
                ('owner_address', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42)),
                ('balance', models.DecimalField(decimal_places=6, max_digits=18)),
            ],
        ),
    ]
