# Generated by Django 4.2.5 on 2023-10-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='actionTokensNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='project',
            name='tokenPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='project',
            name='totalFunds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
